version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: shop_redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - shop_network

volumes:
  redis-data:

networks:
  shop_network:
    driver: bridge
